metadata:
  name: vertx-dns-cluster-test
  labels:
    app: vertx-dns-cluster-test
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 3600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - vertx
        from:
          kind: ImageStreamTag
          namespace: myproject
          name: 'vertx-dns-cluster-test:latest'
  replicas: 3
  revisionHistoryLimit: 2
  test: false
  selector:
    app: vertx-dns-cluster-test
    group: com.redhat.labs
    provider: fabric8
  template:
    spec:
      containers:
        - name: vertx
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: infinispan
              containerPort: 8888
              protocol: TCP
            - name: jolokia
              containerPort: 8778
              protocol: TCP
            - name: eventbus
              containerPort: 5600
              protocol: TCP
          env:
            - name: JAVA_ARGS
              value: "-Djgroups.dns.query=vertx-dns-cluster-test-jgroups.myproject.svc.cluster.local -Djgroups.dns.address=172.30.0.1 -Djava.net.preferIPv4Stack=true -cluster"
          resources: {}
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}